#!/bin/bash

# Set the name of the Python script file
PYFILE="main.py"

# Check if the file exists
if [ -f "$PYFILE" ]; then
    # Run the Python script
    python "$PYFILE"
else
    echo "File not found: $PYFILE"
fi
